/*
 * EazyShop Products APIs Definition
 * # About us `Using` this OpenAPI specification, any consumer can understand the _APIs_ that are exposed by **EasyShop** #Categories supported - Mobile   - Apple   - Samsung   - OnePlus - Laptops - TVs - HeadPhones ``` test highlight  multiline ``` 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: support@eazyshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Category;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CategoriesApi
 */
@Ignore
public class CategoriesApiTest {

    private final CategoriesApi api = new CategoriesApi();

    /**
     * List all categories
     *
     * Returns the list of categories supported by EasyShop
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllCategoriesTest() throws Exception {
        Integer categoryId = null;
        List<Category> response = api.getAllCategories(categoryId);

        // TODO: test validations
    }
    /**
     * Select category by Id
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCategoryDetailsTest() throws Exception {
        Integer categoryId = null;
        Category response = api.getCategoryDetails(categoryId);

        // TODO: test validations
    }
}
