/*
 * EazyShop Products APIs Definition
 * # About us `Using` this OpenAPI specification, any consumer can understand the _APIs_ that are exposed by **EasyShop** #Categories supported - Mobile   - Apple   - Samsung   - OnePlus - Laptops - TVs - HeadPhones ``` test highlight  multiline ``` 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: support@eazyshop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse2001;
import io.swagger.client.model.InlineResponse201;
import io.swagger.client.model.OneOfOrderBody;
import io.swagger.client.model.OrdersBody;
import io.swagger.client.model.OrdersBody1;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for OrdersApi
 */
@Ignore
public class OrdersApiTest {

    private final OrdersApi api = new OrdersApi();

    /**
     * Delete Order
     *
     * Delete order  for Eawyshop 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deletedOrderDetailsTest() throws Exception {
        Integer orderId = null;
        api.deletedOrderDetails(orderId);

        // TODO: test validations
    }
    /**
     * Get Order Details
     *
     * Get Order Details based on Order ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void exampleAnyOfTest() throws Exception {
        Integer orderId = null;
        String fetchType = null;
        InlineResponse2001 response = api.exampleAnyOf(orderId, fetchType);

        // TODO: test validations
    }
    /**
     * Insert oneOf the Order Details
     *
     * Insert oneOf the Order Details into EazyShop
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void exampleOneOfTest() throws Exception {
        OneOfOrderBody body = null;
        api.exampleOneOf(body);

        // TODO: test validations
    }
    /**
     * Get Order
     *
     * Get order  for Eawyshop 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getOrderDetailsTest() throws Exception {
        Integer orderId = null;
        InlineResponse200 response = api.getOrderDetails(orderId);

        // TODO: test validations
    }
    /**
     * Get Order
     *
     * Get order  for Eawyshop 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getOrderDetailsUsingPathParamTest() throws Exception {
        Integer orderId = null;
        OrdersBody response = api.getOrderDetailsUsingPathParam(orderId);

        // TODO: test validations
    }
    /**
     * Create Order
     *
     * Post order details to Eawyshop for processing  and shipping 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void savedOrderDetailsTest() throws Exception {
        OrdersBody1 body = null;
        InlineResponse201 response = api.savedOrderDetails(body);

        // TODO: test validations
    }
    /**
     * Update Order
     *
     * Update order details to Eawyshop for processing  and shipping 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updatedOrderDetailsTest() throws Exception {
        OrdersBody body = null;
        api.updatedOrderDetails(body);

        // TODO: test validations
    }
}
